<a href="https://colab.research.google.com/github/SolbiChoi/test_deeplearning/blob/master/diff_sigmoid_softmax.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Sigmoid

In [1]:
import tensorflow as tf

In [10]:
a = tf.constant([4.0, 1.0, 3.0], dtype = tf.float32)
a, type(a)

(<tf.Tensor: shape=(3,), dtype=float32, numpy=array([4., 1., 3.], dtype=float32)>,
 tensorflow.python.framework.ops.EagerTensor)

In [11]:
b = tf.keras.activations.sigmoid(a)
b

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0.98201376, 0.7310586 , 0.95257413], dtype=float32)>

In [12]:
b.numpy()

array([0.98201376, 0.7310586 , 0.95257413], dtype=float32)

## softmax

In [19]:
inputs = tf.random.normal(shape=(1, 3))
inputs

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[ 0.05342698, -0.692308  ,  0.18183856]], dtype=float32)>

In [20]:
outputs = tf.keras.activations.softmax(inputs)
# outputs

In [21]:
outputs.numpy()

array([[0.3829354 , 0.18165901, 0.43540555]], dtype=float32)

In [ ]:
tf.reduce_sum(outputs[0, :])  # Each sample in the batch now sums to 1