<a href="https://colab.research.google.com/github/SolbiChoi/test_deeplearning/blob/master/NaverSentimentAnalysis_LoadModel_LSTM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [94]:
import tensorflow as tf

In [95]:
loaded_model = tf.keras.models.load_model('./NaverSentimentAnalysis_LSTM.h5')
loaded_model

In [96]:
# !python -m pip install konlpy

In [97]:
import pickle
stopwords = pickle.load(open('./stopwords.pkl','rb'))
print(stopwords)

['의', '가', '이', '은', '들', '는', '좀', '잘', '걍', '과', '도', '를', '으로', '자', '에', '와', '한', '하다']


In [98]:
import konlpy

In [99]:
okt = konlpy.tag.Okt()

In [100]:
# 감독이 예술이네. -> 웹 사용자 입력.
new_sentence = okt.morphs('감독이 예술이네.', stem=True)  # 전처리에서 사용한것과 같은 옵션으로 사용

In [101]:
# words = list()  # tok을 담을 list
# for tok in temp_x:
#   if tok not in stopwords:
#     words.append(tok)

In [102]:
# 불용어 처리
new_sentence = [ tok for tok in new_sentence if tok not in stopwords ]
new_sentence

['감독', '예술', '이네', '.']

In [103]:
tokenizer = pickle.load(open('./tokenizer.pkl','rb'))
tokenizer

# padding

In [107]:
encoded = tokenizer.texts_to_sequences([new_sentence])
# encoded
pad_new = tf.keras.preprocessing.sequence.pad_sequences(encoded, maxlen=50)
pad_new

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,  92, 128,   1]],
      dtype=int32)

# predict

In [108]:
# ['감독이 예술이네.']
score = loaded_model.predict(pad_new)
score

array([[0.48630244]], dtype=float32)

# service

In [109]:
if (score>0.5):
  print('긍정',score*100)
else:
  print('부정',score)

부정 [[0.48630244]]


In [110]:
okt = konlpy.tag.Okt()
new_sentence = okt.morphs('감독이 예술이네.', stem=True)
new_sentence = [ tok for tok in new_sentence if tok not in stopwords ]
encoded = tokenizer.texts_to_sequences([new_sentence])
pad_new = tf.keras.preprocessing.sequence.pad_sequences(encoded, maxlen=50)
score = loaded_model.predict(pad_new)

In [111]:
# 위에꺼 function 화
def sentiment_predict(sentence):
  okt = konlpy.tag.Okt()
  new_sentence = okt.morphs(sentence, stem=True)
  new_sentence = [ tok for tok in new_sentence if tok not in stopwords ]
  encoded = tokenizer.texts_to_sequences([new_sentence])
  pad_new = tf.keras.preprocessing.sequence.pad_sequences(encoded, maxlen=50)
  score = loaded_model.predict(pad_new)
  return score

In [112]:
words = '이 영화 꽝이네.'
sentiment_predict(words)

array([[0.48776603]], dtype=float32)