<a href="https://colab.research.google.com/github/SolbiChoi/test_deeplearning/blob/master/Notescale_LSTM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
note_seq = ['g8', 'e8', 'e4', 'f8', 'd8', 'd4', 'c8', 'd8', 'e8', 'f8', 'g8', 'g8', 'g4',
       'g8', 'e8', 'e8', 'e8', 'f8', 'd8', 'd4', 'c8', 'e8', 'g8', 'g8', 'e8', 'e8', 'e4',
       'd8', 'd8', 'd8', 'd8', 'd8', 'e8', 'f4', 'e8', 'e8', 'e8', 'e8', 'e8', 'f8', 'g4',
       'g8', 'e8', 'e4', 'f8', 'd8', 'd4', 'c8', 'e8', 'g8', 'g8', 'e8', 'e8', 'e4']

In [ ]:
note_seq[0:4], note_seq[1:5], note_seq[2:6]

(['g8', 'e8', 'e4', 'f8'], ['e8', 'e4', 'f8', 'd8'], ['e4', 'f8', 'd8', 'd4'])

In [ ]:
code2idx = {'c4':0, 'd4':1, 'e4':2, 'f4':3, 'g4':4, 'a4':5, 'b4':6,
            'c8':7, 'd8':8, 'e8':9, 'f8':10, 'g8':11, 'a8':12, 'b8':13}

[4,8,12,...]

In [ ]:
len(note_seq), range(len(note_seq)-4)

(54, range(0, 50))

In [ ]:
code2idx['g8']

11

In [ ]:
dataset = list()
for i in range(len(note_seq)-4):
  subset = note_seq[i:i+4]
  items = list()
  # print(subset)
  for item in subset:
    # code2idx[item]
    # print(code2idx[item])
    items.append(code2idx[item])
  # print(items)
  dataset.append(items)

print(dataset)

[[11, 9, 2, 10], [9, 2, 10, 8], [2, 10, 8, 1], [10, 8, 1, 7], [8, 1, 7, 8], [1, 7, 8, 9], [7, 8, 9, 10], [8, 9, 10, 11], [9, 10, 11, 11], [10, 11, 11, 4], [11, 11, 4, 11], [11, 4, 11, 9], [4, 11, 9, 9], [11, 9, 9, 9], [9, 9, 9, 10], [9, 9, 10, 8], [9, 10, 8, 1], [10, 8, 1, 7], [8, 1, 7, 9], [1, 7, 9, 11], [7, 9, 11, 11], [9, 11, 11, 9], [11, 11, 9, 9], [11, 9, 9, 2], [9, 9, 2, 8], [9, 2, 8, 8], [2, 8, 8, 8], [8, 8, 8, 8], [8, 8, 8, 8], [8, 8, 8, 9], [8, 8, 9, 3], [8, 9, 3, 9], [9, 3, 9, 9], [3, 9, 9, 9], [9, 9, 9, 9], [9, 9, 9, 9], [9, 9, 9, 10], [9, 9, 10, 4], [9, 10, 4, 11], [10, 4, 11, 9], [4, 11, 9, 2], [11, 9, 2, 10], [9, 2, 10, 8], [2, 10, 8, 1], [10, 8, 1, 7], [8, 1, 7, 9], [1, 7, 9, 11], [7, 9, 11, 11], [9, 11, 11, 9], [11, 11, 9, 9]]


In [ ]:
import numpy as np
datasets = np.array(dataset)

In [ ]:
x_train = datasets[:,0:3]
x_train.shape

(50, 3)

In [ ]:
y_train = datasets[:,3]
y_train.shape

(50,)

In [ ]:
len(code2idx)

14

In [ ]:
x_train = x_train/13 # len(code2index) 정규화
x_train[3]

array([0.76923077, 0.61538462, 0.07692308])

# make model

In [ ]:
import tensorflow as tf

In [ ]:
x_train.shape  # input의 사이즈를 알기위해 (=3 -> column의 값), tensorflow type(tensor) (50,3,1)
x_train[2] # -> metrix 모양

array([0.15384615, 0.76923077, 0.61538462])

In [ ]:
X_train = np.reshape(x_train, (50,3,1))  # tensor 모양 (갯수,행,열)
X_train.shape, X_train[2]

((50, 3, 1), array([[0.15384615],
        [0.76923077],
        [0.61538462]]))

In [ ]:
np.unique(y_train)

array([ 1,  2,  3,  4,  7,  8,  9, 10, 11])

In [36]:
model = tf.keras.models.Sequential()

tf.keras.Input(shape=(3,1))
model.add(tf.keras.layers.Dense(13,activation='softmax'))  # output layer
# (batch_size , timesteps, input_dim) -> (rows, cols:행의 갯수, 1) -> tensorflow 의 모양
model.add(tf.keras.layers.LSTM(128))  # hidden layer
model.add(tf.keras.layers.Dense(13,activation='softmax'))  # output layer

model.compile(optimizer='adam',loss='sparse_categorical_crossentropy', metrics=['accuracy'])  # gadget

In [37]:
hist = model.fit(X_train, y_train, epochs=2, batch_size=5)

Epoch 1/2
10/10 [==============================] - 1s 4ms/step - loss: 2.5371 - accuracy: 0.3200 
Epoch 2/2
10/10 [==============================] - 0s 3ms/step - loss: 2.4650 - accuracy: 0.3400


In [38]:
model.evaluate(X_train, y_train)

2/2 [==============================] - 1s 8ms/step - loss: 2.4145 - accuracy: 0.3400


[2.414494037628174, 0.3400000035762787]

In [41]:
model.predict(X_train[4:5])

array([[0.06470728, 0.07896752, 0.07399361, 0.07011051, 0.06844176,
        0.06730586, 0.06953678, 0.07783719, 0.09000341, 0.10409005,
        0.07782954, 0.08868596, 0.06849046]], dtype=float32)