<a href="https://colab.research.google.com/github/SolbiChoi/test_deeplearning/blob/master/wine_deeplearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. Store data to DB

In [1]:
from sklearn import datasets

In [2]:
wine = datasets.load_wine()
wine.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names'])

In [3]:
x_data = wine['data']
x_data.shape

(178, 13)

In [4]:
y_data = wine['target']
y_data

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

In [5]:
import numpy as np
np.unique(y_data)

array([0, 1, 2])

## Table (data, target)

In [6]:
import pandas as pd
df_wine = pd.DataFrame(wine.data, columns=wine['feature_names'])
df_wine.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 13 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   alcohol                       178 non-null    float64
 1   malic_acid                    178 non-null    float64
 2   ash                           178 non-null    float64
 3   alcalinity_of_ash             178 non-null    float64
 4   magnesium                     178 non-null    float64
 5   total_phenols                 178 non-null    float64
 6   flavanoids                    178 non-null    float64
 7   nonflavanoid_phenols          178 non-null    float64
 8   proanthocyanins               178 non-null    float64
 9   color_intensity               178 non-null    float64
 10  hue                           178 non-null    float64
 11  od280/od315_of_diluted_wines  178 non-null    float64
 12  proline                       178 non-null    float64
dtypes: fl

In [7]:
df_wine

alcohol  malic_acid   ash  ...   hue  od280/od315_of_diluted_wines  proline
0      14.23        1.71  2.43  ...  1.04                          3.92   1065.0
1      13.20        1.78  2.14  ...  1.05                          3.40   1050.0
2      13.16        2.36  2.67  ...  1.03                          3.17   1185.0
3      14.37        1.95  2.50  ...  0.86                          3.45   1480.0
4      13.24        2.59  2.87  ...  1.04                          2.93    735.0
..       ...         ...   ...  ...   ...                           ...      ...
173    13.71        5.65  2.45  ...  0.64                          1.74    740.0
174    13.40        3.91  2.48  ...  0.70                          1.56    750.0
175    13.27        4.28  2.26  ...  0.59                          1.56    835.0
176    13.17        2.59  2.37  ...  0.60                          1.62    840.0
177    14.13        4.10  2.74  ...  0.61                          1.60    560.0

[178 rows x 13 columns]

In [8]:
import sqlite3
connect = sqlite3.connect('./db.sqlite3')

In [9]:
df_wine.to_sql('wine_resource', connect, if_exists='append', index=False)

# 2. DB에서 data 불러오기 (load data)

## (1) Data 전처리

## (2) x,y 로 쪼개기 (split)

In [10]:
df_load = pd.read_sql_query('select * from wine_resource', connect)
df_load.head(3)

alcohol  malic_acid   ash  ...   hue  od280/od315_of_diluted_wines  proline
0    14.23        1.71  2.43  ...  1.04                          3.92   1065.0
1    13.20        1.78  2.14  ...  1.05                          3.40   1050.0
2    13.16        2.36  2.67  ...  1.03                          3.17   1185.0

[3 rows x 13 columns]

In [11]:
x_data = df_load.to_numpy()
x_data.shape

(178, 13)

In [12]:
y_data = wine.target
y_data, np.unique(y_data)

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2]), array([0, 1, 2]))

# 3. Deeplearning

### model 만들기

In [13]:
import tensorflow as tf

In [14]:
model = tf.keras.Sequential()

model.add(tf.keras.Input(shape=13,))  # input layer

model.add(tf.keras.layers.Dense(64, activation='relu'))  # hidden layer
model.add(tf.keras.layers.Dense(128, activation='relu'))  # hidden layer
# model.add(tf.keras.layers.Dense(64, activation='relu'))
model.add(tf.keras.layers.Dense(32, activation='relu'))  # hidden layer (항아리 모양으로 만들기)

model.add(tf.keras.layers.Dense(3, activation='softmax'))  # output layer

model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['acc'])

In [15]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 64)                896       
_________________________________________________________________
dense_1 (Dense)              (None, 128)               8320      
_________________________________________________________________
dense_2 (Dense)              (None, 64)                8256      
_________________________________________________________________
dense_3 (Dense)              (None, 32)                2080      
_________________________________________________________________
dense_4 (Dense)              (None, 3)                 99        
Total params: 19,651
Trainable params: 19,651
Non-trainable params: 0
_________________________________________________________________


# 4. 교육

In [16]:
model.fit(x_data, y_data, epochs=500, validation_split=0.3)

Epoch 1/500
4/4 [==============================] - 1s 65ms/step - loss: 12.7721 - acc: 0.4677 - val_loss: 53.2744 - val_acc: 0.0000e+00
Epoch 2/500
4/4 [==============================] - 0s 9ms/step - loss: 6.5864 - acc: 0.6210 - val_loss: 28.6882 - val_acc: 0.1111
Epoch 3/500
4/4 [==============================] - 0s 10ms/step - loss: 6.7034 - acc: 0.6048 - val_loss: 31.5675 - val_acc: 0.0370
Epoch 4/500
4/4 [==============================] - 0s 8ms/step - loss: 5.7039 - acc: 0.5000 - val_loss: 32.9065 - val_acc: 0.0185
Epoch 5/500
4/4 [==============================] - 0s 9ms/step - loss: 2.4259 - acc: 0.6855 - val_loss: 23.0541 - val_acc: 0.1111
Epoch 6/500
4/4 [==============================] - 0s 9ms/step - loss: 3.0355 - acc: 0.6613 - val_loss: 21.3752 - val_acc: 0.0926
Epoch 7/500
4/4 [==============================] - 0s 10ms/step - loss: 2.4375 - acc: 0.6452 - val_loss: 22.9922 - val_acc: 0.0926
Epoch 8/500
4/4 [==============================] - 0s 9ms/step - loss: 1.3654 - ac

# 5. 검증 (Evaluation)

In [17]:
# model.evaluate(x_data, y_data)  # epochs=50 - loss: 54.4796 - acc: 0.6404

In [18]:
# model.evaluate(x_data, y_data)  # epochs=100 - loss: 11.6780 - acc: 0.6854

In [19]:
#  model.evaluate(x_data, y_data)  # epochs=500 - loss: 11.8336 - acc: 0.6798

In [20]:
model.evaluate(x_data, y_data)  # epochs=500, hidden layer 추가 (val 128) - loss: 10.4153 - acc: 0.7135

In [21]:
# model.evaluate(x_data, y_data)  # epochs=500, hidden layer 추가 (val 128, 64) - loss: 5.6670 - acc: 0.6798

6/6 [==============================] - 0s 2ms/step - loss: 5.6670 - acc: 0.6798


[5.6670098304748535, 0.6797752976417542]

# 6. 서비스 (predict)

In [22]:
x_data[30], y_data[30]

(array([1.373e+01, 1.500e+00, 2.700e+00, 2.250e+01, 1.010e+02, 3.000e+00,
        3.250e+00, 2.900e-01, 2.380e+00, 5.700e+00, 1.190e+00, 2.710e+00,
        1.285e+03]), 0)

In [23]:
pred = model.predict([[1.373e+01, 1.500e+00, 2.700e+00, 2.250e+01, 1.010e+02, 3.000e+00,
        3.250e+00, 2.900e-01, 2.380e+00, 5.700e+00, 1.190e+00, 2.710e+00,
        1.285e+03]])
pred

array([[9.9994421e-01, 5.5755678e-05, 3.1954276e-24]], dtype=float32)

In [24]:
np.argmax(pred)

0